apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure-operations-team
  description: Infrastructure Operations Team
spec:
  type: team
  profile:
    displayName: Infrastructure Operations
    email: infra-ops@tap.tanzu.xyz
    picture: https://raw.githubusercontent.com/uki-tanzu-se/tap-gui-catalog/main/img/org-logo%400.5x.png
  parent: uki-tanzu-se-org
  children: []
